import type { Recommendation } from '@/types';

export const RECOMMENDATION_TEMPLATES: Omit<Recommendation, 'isAdopted'>[] = [
  // Transport
  {
    id: 'public-transit-2d',
    category: 'transport',
    title: 'Public transit 2 days/week',
    description: 'Switch from driving a car to public transit (bus or train) twice a week.',
    estimatedReduction: 45,
    difficulty: 'easy',
    timeToAdopt: 'oneWeek',
    costImpact: 'savesMoney',
    whyItMatters: 'Public transportation has a much lower carbon footprint per passenger-km compared to single-occupancy petrol vehicles.',
  },
  {
    id: 'bike-to-work-3d',
    category: 'transport',
    title: 'Cycle or walk to work 3 days/week',
    description: 'Active travel for commutes under 5km instead of driving.',
    estimatedReduction: 60,
    difficulty: 'medium',
    timeToAdopt: 'oneWeek',
    costImpact: 'savesMoney',
    whyItMatters: 'Biking and walking produce zero operational emissions while improving health and fitness.',
  },
  {
    id: 'carpool-commute',
    category: 'transport',
    title: 'Carpool with colleagues',
    description: 'Share your daily commute with one or more coworkers.',
    estimatedReduction: 30,
    difficulty: 'easy',
    timeToAdopt: 'oneWeek',
    costImpact: 'savesMoney',
    whyItMatters: 'Splitting travel emissions among multiple passengers immediately cuts your personal footprint per trip.',
  },
  
  // Food
  {
    id: 'meatless-monday',
    category: 'food',
    title: 'Meatless day once a week',
    description: 'Replace meat with plant-based alternatives (beans, lentils, tofu) one day every week.',
    estimatedReduction: 15,
    difficulty: 'easy',
    timeToAdopt: 'immediate',
    costImpact: 'savesMoney',
    whyItMatters: 'Beef and lamb production produce up to 30x more greenhouse gases per kg than plant-based protein sources.',
  },
  {
    id: 'go-vegetarian',
    category: 'food',
    title: 'Switch to a vegetarian diet',
    description: 'Remove meat and fish from your diet entirely.',
    estimatedReduction: 50,
    difficulty: 'hard',
    timeToAdopt: 'oneMonth',
    costImpact: 'savesMoney',
    whyItMatters: 'Adopting a vegetarian diet cuts food-related emissions by roughly 47% compared to average meat diets.',
  },
  {
    id: 'buy-local-organic',
    category: 'food',
    title: 'Buy local & seasonal produce',
    description: 'Source 50% or more of your fruits and vegetables from local farmers or seasonal markets.',
    estimatedReduction: 8,
    difficulty: 'easy',
    timeToAdopt: 'oneWeek',
    costImpact: 'noCost',
    whyItMatters: 'Reduces the food-miles (transport emissions) and high-energy refrigeration required for off-season imports.',
  },
  {
    id: 'reduce-food-waste',
    category: 'food',
    title: 'Plan meals to eliminate waste',
    description: 'Plan your weekly grocery list and store food properly to achieve zero waste.',
    estimatedReduction: 12,
    difficulty: 'easy',
    timeToAdopt: 'oneWeek',
    costImpact: 'savesMoney',
    whyItMatters: 'Around 30% of global food is wasted. Wasted food decaying in landfills produces methane, a potent greenhouse gas.',
  },

  // Energy
  {
    id: 'switch-led-bulbs',
    category: 'energy',
    title: 'Switch to LED lighting',
    description: 'Replace all remaining incandescent or halogen bulbs with energy-efficient LEDs.',
    estimatedReduction: 5,
    difficulty: 'easy',
    timeToAdopt: 'immediate',
    costImpact: 'smallCost',
    whyItMatters: 'LED bulbs use up to 80% less energy and last up to 25 times longer than traditional incandescent bulbs.',
  },
  {
    id: 'unplug-vampire-appliances',
    category: 'energy',
    title: 'Unplug standby electronics',
    description: 'Turn off or unplug chargers, consoles, and appliances when not in use.',
    estimatedReduction: 4,
    difficulty: 'easy',
    timeToAdopt: 'immediate',
    costImpact: 'noCost',
    whyItMatters: 'Standby or "vampire" power accounts for up to 10% of household electricity bills.',
  },
  {
    id: 'adjust-thermostat-1c',
    category: 'energy',
    title: 'Adjust thermostat by 1°C',
    description: 'Set your AC 1°C warmer in summer or heating 1°C cooler in winter.',
    estimatedReduction: 12,
    difficulty: 'easy',
    timeToAdopt: 'immediate',
    costImpact: 'savesMoney',
    whyItMatters: 'A 1°C temperature shift can reduce the energy used for heating and cooling by up to 10%.',
  },
  {
    id: 'green-electricity-tariff',
    category: 'energy',
    title: 'Switch to renewable energy source',
    description: 'Switch your utility provider to a 100% renewable electricity tariff or install solar panels.',
    estimatedReduction: 100,
    difficulty: 'hard',
    timeToAdopt: 'oneMonth',
    costImpact: 'smallCost',
    whyItMatters: 'Transitioning to wind, water, or solar power virtually eliminates household electricity emissions.',
  },

  // Shopping
  {
    id: 'buy-second-hand',
    category: 'shopping',
    title: 'Choose second-hand first',
    description: 'Look for used, vintage, or refurbished alternatives before buying new clothes or electronics.',
    estimatedReduction: 10,
    difficulty: 'easy',
    timeToAdopt: 'oneWeek',
    costImpact: 'savesMoney',
    whyItMatters: 'Buying pre-owned items bypasses the carbon emissions generated during raw material extraction, manufacturing, and shipping.',
  },
  {
    id: 'reduce-fast-fashion',
    category: 'shopping',
    title: 'Cut new clothing purchases by half',
    description: 'Focus on high-quality, durable garments and reduce impulse fashion purchases.',
    estimatedReduction: 8,
    difficulty: 'medium',
    timeToAdopt: 'oneMonth',
    costImpact: 'savesMoney',
    whyItMatters: 'The fashion industry is responsible for 8-10% of global carbon emissions, heavily driven by synthetic fabrics and rapid disposal.',
  },

  // Waste
  {
    id: 'start-recycling',
    category: 'waste',
    title: 'Separate recyclable waste',
    description: 'Consistently sort paper, cardboard, glass, metals, and plastics.',
    estimatedReduction: 6,
    difficulty: 'easy',
    timeToAdopt: 'oneWeek',
    costImpact: 'noCost',
    whyItMatters: 'Recycling metals and plastics consumes far less energy than extracting and refining virgin raw materials.',
  },
  {
    id: 'start-composting',
    category: 'waste',
    title: 'Compost organic waste',
    description: 'Set up a backyard compost bin or use local organic collection for food scraps.',
    estimatedReduction: 4,
    difficulty: 'medium',
    timeToAdopt: 'oneWeek',
    costImpact: 'smallCost',
    whyItMatters: 'Composted food scraps break down aerobically (producing carbon dioxide) rather than anaerobically in landfills (producing potent methane).',
  },
  {
    id: 'eliminate-plastic-bags',
    category: 'waste',
    title: 'Eliminate single-use plastic bags',
    description: 'Keep reusable shopping bags in your car or backpack for groceries.',
    estimatedReduction: 3,
    difficulty: 'easy',
    timeToAdopt: 'immediate',
    costImpact: 'noCost',
    whyItMatters: 'Single-use plastics are produced from fossil fuels, have high manufacturing footprints, and persist in the environment for centuries.',
  },

  // Travel
  {
    id: 'train-instead-of-flight',
    category: 'travel',
    title: 'Take the train instead of short flights',
    description: 'For travel distances under 600km, choose high-speed rail instead of domestic flights.',
    estimatedReduction: 80,
    difficulty: 'medium',
    timeToAdopt: 'oneMonth',
    costImpact: 'noCost',
    whyItMatters: 'Train travel produces up to 85% less carbon per passenger-km compared to flying short distances.',
  },
  {
    id: 'reduce-non-essential-travel',
    category: 'travel',
    title: 'Reduce long-distance travel by 1 flight',
    description: 'Opt for virtual meetings or choose local vacation destinations to skip one flight this year.',
    estimatedReduction: 150,
    difficulty: 'hard',
    timeToAdopt: 'oneMonth',
    costImpact: 'savesMoney',
    whyItMatters: 'A single long-haul flight can produce more carbon than a person in some developing countries produces in an entire year.',
  },
];
